### ISSUE TITLE
TypeError: compute_accuracy_metrics() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by randomstudentid** [i6092467/diff-bias-proxies#1]
Hello,

Congrats on your very interesting paper!

I was trying to run the code provided and I encountered the following error:

```
Traceback (most recent call last):
  File "main_ChestXRay.py", line 738, in <module>
    main(config)
  File "main_ChestXRay.py", line 107, in main
    model, train_acc, train_loss, val_acc, val_loss = train_ChestXRay_model(
  File "/diff-bias-proxies/models/networks_ChestXRay.py", line 348, in train_ChestXRay_model
    auroc, avg_precision, balanced_acc, f1_acc = compute_accuracy_metrics(probs_mat, preds_vec, labels_vec,
TypeError: compute_accuracy_metrics() takes 2 positional arguments but 4 were given
```

Indeed, the function compute_accuracy_metrics is defined with only two arguments in the file utils/evaluation.py.

**Comment by i6092467** [comment]
Thank you for pointing out the issue. The code has been updated. Let me know if any further issues arise!
